---
- name: install and configure apache2
  hosts: # TBD
  become: yes
  become_user: root  
  roles:
     - users 
     - patching 
     - packages 
     - docker
     - docker-compose
     - apache2
     - reboot
