# apache_server/tasks/main.yml

---
- name: Install web server
  package:
    name: "{{ web_server_type }}"
    state: present
  notify: Restart {{ web_server_type }}

- name: Start and enable the web server service
  systemd:
    name: "{{ web_server_type }}"
    enabled: yes
    state: started
  notify: Restart {{ web_server_type }}


