# apache_server/tasks/main.yml

---
- name: Install Apache packages
  apt:
    name: apache2
    state: present

- name: Start and enable Apache service
  service:
    name: apache2
    state: started
    enabled: yes

