# user_management/tasks/main.yml
---
- name: Create a group
  group:
    name: "{{ group_name }}"
    state: present
  become: yes

- name: Create a user
  user:
    name: "{{ user_name }}"
    group: "{{ group_name }}"
    state: present
    createhome: yes
  become: yes  
