# user_management/tasks/main.yml
---
- name: Create groups
  group:
    name: "{{ item.name }}"
  with_items: "{{ groups }}"

- name: Create users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups | default([]) }}"
    password: "{{ item.password }}"
  with_items: "{{ users }}"
  notify: restart some_service # Optionally, notify a service to restart

- name: Ensure users are in their respective groups
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default([]) }}"
    append: yes
  with_items: "{{ users }}"
  when: item.groups is defined

